stages:
  - build
  - test

variables:
  MYSQL_ROOT_PASSWORD: root

services:
  - name: mariadb:latest
    alias: mariadb
  - name: node:latest
    alias: node

build: &build
  stage: build
  image: yarnpkg/node-yarn:latest
  script:
    - npm install yarn
    - yarn install

build-front:
  stage: build
  <<: *build
  script:
    - yarn start-fronted-prod

build-back:
  stage: build
  <<: *build
  script:
    - yarn start-backend-prod

test:
  stage: test
  image: yarnpkg/node-yarn:latest
  script:
    - docker-compose -f /backend-nest/docker-compose.dev.yaml up --build -d
#    - yarn test TODO
    - docker-compose -f /backend-nest/docker-compose.dev.yaml down



