stages:
  - build
  - test

variables:
  MYSQL_ROOT_PASSWORD: root

services:
  - name: mariadb:latest
    alias: mariadb
  - name: node:latest
    alias: node

build: &build
  stage: build
  image: yarnpkg/node-yarn:latest
  script:
    - yarn -v
    - yarn install

build-front:
  stage: build
  <<: *build
  script:
    - npm install -g @vue/cli
    - yarn build-frontend-prod

build-back:
  stage: build
  <<: *build
  script:
    - npm i -g @nestjs/cli
    - yarn build-backend-prod

test:
  stage: test
  image: yarnpkg/node-yarn:latest
  script:
    - docker-compose -f /backend-nest/docker-compose.dev.yaml up --build -d
#    - yarn test TODO
    - docker-compose -f /backend-nest/docker-compose.dev.yaml down



