stages:
  - build
  - test

variables:
  MYSQL_ROOT_PASSWORD: root

services:
  - name: mariadb:latest
    alias: mariadb
  - name: node:latest
    alias: node

build: &build
  stage: build
  image: node:slim
  script:
    - yarn -v

build-front:
  stage: build
  <<: *build
  before_script:
    - yarn install
  script:
    - yarn build-frontend-prod

build-back:
  stage: build
  <<: *build
  before_script:
    - yarn install
  script:
    - yarn build-backend-prod

test:
  stage: test
  image: ubuntu:latest
  script:
    - docker-compose -f /backend-nest/docker-compose.dev.yaml up --build -d
    - yarn test TODO
    - docker-compose -f /backend-nest/docker-compose.dev.yaml down



