# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: mariadb
    command: --max_allowed_packet=32505856 --max-connections=10000
    environment:
      MYSQL_USER: adminer
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: sae5
      MYSQL_ROOT_PASSWORD: example

    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 7777:8080